<html>
<head>
    <meta charset="utf-8"/>
    <title>Edit Book "<?php echo $book->name ?>"</title>
    <link href='/resources/bootstrap/dist/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="container">
    <h1>Edit Book "<?php echo $book->name ?>"</h1>
    <div class="row">
        <div class="col-lg-12">
            <form method="post" action="/book/<?php echo $book->id?>" class="form-group">
                <label class="control-label" for="name">Book`s name</label>
                <input type="text" name="name" required class="form-control" value="<?php echo $book->name ?>">
                <label class="control-label" for="author_id">Choose author</label>
                <select name="author_id" class="form-control">
                    <?php foreach($authors as $author) { ?>
                        <?php if ( $book->author_id == $author->id ) {
                            ?>
                            <option selected value="<?php echo $author->id; ?>"><?php echo $author->firstname . ' ' . $author->lastname; ?> </option>
                        <?php } else { ?>
                            <option value="<?php echo $author->id; ?>"><?php echo $author->firstname . ' ' . $author->lastname; ?> </option>
                            <?php } ?>
                    <?php } ?>
                </select>
                <input type="submit" value="Save" class="btn btn-default" style="margin-top: 10px;">
            </form>
        </div>
    </div>
</div>
</body>
</html>
